### ISSUE TITLE
Allow overwriting of freeze files

### ISSUE THREAD

**Issue by Azrael3000** [tmux-python/tmuxp#64]
Currently tmuxp doesn't allow that, so it might be nice to support that.

I'm going to send you a few more issues with enhancements that I thought off. None of it is essential but it would improve the overall handling imho. I'm going to open each in a different issue so that it is easier for you to keep track of things.

**Comment by sakalys** [comment]
How do we reopen this?

**Comment by tony** [comment]
@sakalys Reopened

**Comment by sakalys** [comment]
Currently, if you attempt to freeze and save the config to an existing file, then you are informed that you cannot do so, because the file already exists. I am willing to code and submit a pull request that would allow the tmuxp freeze command to overwrite the specified file.

Does anyone see any problems with this, because I did not look anywhere else in the code except the function responsible for the command?

**Comment by Ma-Nu-El** [comment]
Facing the same need here, it'd be great if `tmuxp freeze` could just overwrite an existing session.

I mean, yeah I could automate the deletion and then `tmuxp freeze` again, but that seems like an unnecessary workaround.

BTW, thanks for 'tmuxp'! It's the icing on the cake of my bash/vim/EmacsOrgmode/tmux workflow! 

Cheers

**Comment by joseph-flinn** [comment]
Thanks for using tmuxp! It seems like `tmuxp freeze --force` solves this issue with the above mentioned PR.
