### ISSUE TITLE
conftest.py should not be part of the package

### ISSUE THREAD

**Issue by dvzrv** [tmux-python/tmuxp#825]
### Step 1: Provide a summary of your problem

When packaging tmuxp for Arch Linux I realized that the conftest.py file is still packaged in the context of tmuxp:
`usr/lib/python3.10/site-packages/tmuxp/conftest.py`.

This file is only used for pytest and should not be part of the package.

### Step 2: Provide tmuxp details

tmuxp 1.15.1

#### Steps to reproduce:

```
python -m build --wheel --no-isolation
python -m installer --destdir="$pkgdir" dist/*.whl
```

#### Observed Results:

`usr/lib/python3.10/site-packages/tmuxp/conftest.py` is packaged.

#### Expected Results:

`usr/lib/python3.10/site-packages/tmuxp/conftest.py` is not packaged

#### Relevant Code:
n/a

**Comment by tony** [comment]
@dvzrv Taking a look - would like to make maintaining the package convenient as possible downstream

FYI - Do you run the tests directly from the source? (the reason why is, if conftest.py is excluded, you won't be able to run the tests - do you use the source itself rather than the built package for running tests?)

Secondly - the package itself has the conftest.py due to us running `doctest` in the source code docstrings. Some examples of this:

- https://github.com/google/jax/blob/main/conftest.py
- https://github.com/numpy/numpy/blob/main/numpy/conftest.py

**Comment by tony** [comment]
@dvzrv Did you see my reply here? https://github.com/tmux-python/libtmux/issues/441#issuecomment-1254342853

**Comment by dvzrv** [comment]
I had to run the tests against a temporary install location as otherwise tmuxp is no longer found.
The conftest.py file can be located in an sdist tarball, but I don't think it should be included in the installed package (e.g. the wheel, or rather what is then actually used by the user later on).

**Comment by tony** [comment]
Keeping open until confirmed fix

Publishing to 1.15.2 to PyPI now

**Comment by tony** [comment]
@dvzrv [v1.15.2](https://pypi.org/project/tmuxp/1.15.2/) now released

Anything different this time?

**Comment by dvzrv** [comment]
Yep that works. Thank you!

**Comment by tony** [comment]
@dvzrv Excellent!
